apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dy63n3678-go
  janus-idp.io/tekton: dy63n3678-go
  backstage.io/kubernetes-id: dy63n3678-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dy63n3678-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
